### ISSUE TITLE
Service fails to start on clean provision as DB tables are missing

### ISSUE THREAD

**Issue by roborourke** [Chassis/Cavalcade#23] opened 2018-10-09 09:02 UTC
1. What operating system do you use?
OSX

2. What version of Vagrant are you running?
2.1.2

3. Are you using VirtualBox or VMWare and which version are you using?
Virtualbox 5.2.16

4. Do you have a custom YAML file? If so, what does it contain?
```yaml
extensions:
  - cavalcade
```

The problem is that the database (even if created) does not contain the cavalcade tables until the site has been visited. The db table creation logic is contained in the plugin rather than the runner, the end result is that on a clean provision when trying to bring up the cavalcade service it fails because those tables are missing. A second provision after visiting the website or running it via a WP CLI command is required to activate the service.

**Comment by roborourke** [comment] 2018-10-10 14:20
Realised this might well be because I have a `WP_INSTALLING` check on the project I noticed this on which means the cavalcade plugin isn't loaded during install.

**Comment by svandragt** [comment] 2019-09-30 15:06
The problem is that this installs the cron runner, but not the WP plugin. Once you install the WP plugin via composer and activate it, then restart the service it runs as expected.

**Comment by roborourke** [comment] 2019-09-30 15:11
@svandragt good catch! Interesting then, there are a good few methods the plugin might be included / activated by. I'm not sure we'd want the extension to install the plugin as it's something the project should include, or at least is in the case of HM projects.

**Comment by BronsonQuick** [comment] 2019-11-13 03:34
Yeah I agree that the extension shouldn't install the plugin as you might want to use it as a plugin, mu-plugin or even autoloaded so I'm going to close this out.

**Closed by BronsonQuick** 2019-11-13 03:34 UTC
Labels: bug
